defmodule KiraBijoux.Repo.Migrations.InsertItems do
  use KiraBijouxWeb, :migration

  def change do
    item_parent1 = Repo.one(from it in Item.Parent, select: it.id, where: it.name == "Aylee")
    item_parent2 = Repo.one(from it in Item.Parent, select: it.id, where: it.name == "Daenerys")
    item_parent3 = Repo.one(from it in Item.Parent, select: it.id, where: it.name == "Selena")
    item_parent4 = Repo.one(from it in Item.Parent, select: it.id, where: it.name == "Eden")
    item_parent5 = Repo.one(from it in Item.Parent, select: it.id, where: it.name == "Isis")
    item_parent6 = Repo.one(from it in Item.Parent, select: it.id, where: it.name == "Vahalla")
    item_parent7 = Repo.one(from it in Item.Parent, select: it.id, where: it.name == "Tanya")
    item_parent8 = Repo.one(from it in Item.Parent, select: it.id, where: it.name == "Kena")
    item_parent9 = Repo.one(from it in Item.Parent, select: it.id, where: it.name == "Meredith")
    item_parent10 = Repo.one(from it in Item.Parent, select: it.id, where: it.name == "Marie")
    item_parent11 = Repo.one(from it in Item.Parent, select: it.id, where: it.name == "Shana")
    item_parent12 = Repo.one(from it in Item.Parent, select: it.id, where: it.name == "Melinda")
    Repo.insert_all(Item,
      [ %{item_parent_id: item_parent1, price: 37.00, stock: 5, visibility: true, subtitle: "Collier Aylee en Argent 925", description: "Une pointe en Argent 925 sur une chaine de 35 cm avec une extension de 5 cm. Un ras de cou fin, tout en Argent 925, qui peut être porté en association avec d'autres colliers plus longs !", length: "35 cm + 5 cm extension", inserted_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second), updated_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second)},
      %{item_parent_id: item_parent2, price: 68.00, stock: 0, visibility: true, subtitle: "Collier Daenerys en perles de Larvikite", description: "Un collier en perles de Larvikite et perles d'Argent 925, tout aussi fin que fort de caractère. Inspiré d'une série bien connue (vous vous en doutiez), le collier <i>Daenerys</i> est un hommage à la reine des dragons. Un ras de cou d'une longueur de 37 cm, avec une chaînette d'extension de 5 cm !", length: "37 cm + 5 cm extension", inserted_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second), updated_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second)},
      %{item_parent_id: item_parent3, price: 38.00, stock: 6, visibility: true, subtitle: "Collier Selena en Argent 925", description: "Une petite lune en Argent 925, finement travaillée, sur une chaîne de 38 cm. Alors que le pendentif lune apporte une touche de rêverie, la longueur de la chaîne apporte au collier <i>Selena</i> un caractère tendre et raffiné. Le prénom Selena découle de Selenê, la déesse de la lune dans la mythologie grecque. Vous aimerez son association à un collier en perles plus court ou à d'autres colliers plus longs.", length: "38 cm", inserted_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second), updated_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second)},
      %{item_parent_id: item_parent4, price: 42.00, stock: 11, visibility: true, subtitle: "Collier Eden en Argent 925", description: "Le collier <i>Eden</i> est composé d'une tête de flèche en Argent 925 sur une chaîne de 38 cm. Une flèche travaillée dans les détails, dans un très bel argent, rendant au collier <i>Eden</i> une dynamique de force et de pouvoir. Vous aimerez son association à un collier en perles plus court ou à d'autres colliers plus longs.", length: "38 cm", inserted_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second), updated_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second)},
      %{item_parent_id: item_parent5, price: 45.00, stock: 10, visibility: true, subtitle: "Collier Isis en Argent 925 et Lapis Lazuli", description: "<i>Isis</i>, c'est une pierre de Lapis Lazuli certie, accompagnée d'un médaillon gravé de petits pissenlits, montée sur une chaîne de 40 cm. Le Lapis Lazuli est une pierre bleue parcemée d'éclats dorés. Le collier <i>Isis</i> est un mélange de finesse et de douceur.", length: "40 cm", inserted_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second), updated_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second)},
      %{item_parent_id: item_parent6, price: 42.00, stock: 6, visibility: true, subtitle: "Collier Vahalla en Argent 925", description: "Une médaille ajourée en Argent 925, travaillée en finesse, sur une chaîne de 40 cm. Une impression d'histoires antiques est ancrée dans le collier <i>Vahalla</i>, lui conférant un style ancien et raffiné. Le collier <i>Vahalla</i> pourra être associé avec des colliers plus courts comme un <i>Shana</i> ou plus long comme un <i>Kena</i>.", length: "40 cm", inserted_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second), updated_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second)},
      %{item_parent_id: item_parent7, price: 39.00, stock: 11, visibility: true, subtitle: "Collier Tanya en Argent 925", description: "Une médaille martelée en Argent 925, sur une chaîne de 45 cm. A la fois finesse et force de caractère, <i>Tanya</i> est un collier qui peut se porter aussi bien au quotidien sur un gros pull en laine qu'en soirée associé à une robe de cocktail ! Vous aimerez son association avec d'autres colliers, mais aussi avec le bracelet Meredith qui propose une médaille assortie.", length: "45 cm", inserted_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second), updated_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second)},
      %{item_parent_id: item_parent8, price: 45.00, stock: 4, visibility: true, subtitle: "Collier Kena en Argent 925 et Amazonite", description: "Pendentif en Amazonite orné d'une pointe en Argent 925, sur une chaîne de 50 cm. Le collier <i>Kena</i> existe en différentes pierres, que vous pouvez découvrir dans la sélection déroulante. Vous aimerez l'association du collier <i>Kena</i> avec d'autres colliers plus courts en Argent 925.", length: "50 cm", inserted_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second), updated_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second)},
      %{item_parent_id: item_parent8, price: 45.00, stock: 6, visibility: true, subtitle: "Collier Kena en Argent 925 et Pierre de lune", description: "Pendentif en Pierre de lune orné d'une pointe en Argent 925, sur une chaîne de 50 cm. Le collier <i>Kena</i> existe en différentes pierres, que vous pouvez découvrir dans la sélection déroulante. Vous aimerez l'association du collier <i>Kena</i> avec d'autres colliers plus courts en Argent 925.", length: "50 cm", inserted_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second), updated_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second)},
      %{item_parent_id: item_parent8, price: 45.00, stock: 5, visibility: true, subtitle: "Collier Kena en Argent 925 et Quartz rose", description: "Pendentif en Quartz rose orné d'une pointe en Argent 925, sur une chaîne de 50 cm. Le collier <i>Kena</i> existe en différentes pierres, que vous pouvez découvrir dans la sélection déroulante. Vous aimerez l'association du collier <i>Kena</i> avec d'autres colliers plus courts en Argent 925.", length: "50 cm", inserted_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second), updated_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second)},
      %{item_parent_id: item_parent8, price: 45.00, stock: 0, visibility: true, subtitle: "Collier Kena en Argent 925 et Amethyste", description: "Pendentif en Amethyste orné d'une pointe en Argent 925, sur une chaîne de 50 cm. Le collier <i>Kena</i> existe en différentes pierres, que vous pouvez découvrir dans la sélection déroulante. Vous aimerez l'association du collier <i>Kena</i> avec d'autres colliers plus courts en Argent 925.", length: "50 cm", inserted_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second), updated_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second)},
      %{item_parent_id: item_parent8, price: 45.00, stock: 6, visibility: true, subtitle: "Collier Kena en Argent 925 et Labradorite", description: "Pendentif en Labradorite orné d'une pointe en Argent 925, sur une chaîne de 50 cm. Le collier <i>Kena</i> existe en différentes pierres, que vous pouvez découvrir dans la sélection déroulante. Vous aimerez l'association du collier <i>Kena</i> avec d'autres colliers plus courts en Argent 925.", length: "50 cm", inserted_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second), updated_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second)},
      %{item_parent_id: item_parent8, price: 45.00, stock: 6, visibility: true, subtitle: "Collier Kena en Argent 925 et Lapis Lazuli", description: "Pendentif en Lapis Lazuli orné d'une pointe en Argent 925, sur une chaîne de 50 cm. Le collier <i>Kena</i> existe en différentes pierres, que vous pouvez découvrir dans la sélection déroulante. Vous aimerez l'association du collier <i>Kena</i> avec d'autres colliers plus courts en Argent 925.", length: "50 cm", inserted_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second), updated_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second)},
      %{item_parent_id: item_parent9, price: 24.00, stock: 11, visibility: true, subtitle: "Bracelet Meredith en Argent 925", description: "Une petite médaille martelée pour un bracelet fin et léger. A porter au quotidien ou pour une soirée chic, le bracelet <i>Meredith</i> allie finesse et caractère. Vous aimerez son association avec le collier <i>Tanya</i> qui propose une médaille assortie.", length: "17,5 cm", inserted_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second), updated_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second)},
      %{item_parent_id: item_parent10, price: 26.00, stock: 5, visibility: true, subtitle: "Boucles d'oreilles Marie en Tourmaline rubellite", description: "Des pendants d'oreilles en pierre de Tourmaline rubellite œil de chat et Argent 925, d'une longueur de 2 cm. L'effet 'œil de chat' donne un effet de transparence à la couleur bleue de la tourmaline rubellite, lui conférant une parfaite brillance. Les boucles d'oreilles <i>Marie</i> peuvent être associées à d'autres bijoux de la marque Kira en Argent 925.", length: "2 cm", inserted_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second), updated_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second)},
      %{item_parent_id: item_parent11, price: 67.00, stock: 1, visibility: true, subtitle: "Collier Shana en perles de Jaspe Kambaba", description: "Un collier en perles de Jaspe Kambaba et perles d'Argent 925, tout en douceur. Le vert sombre de la jaspe kambaba rappelle notre lien à la nature et donne au collier <i>Shana</i> un style tout aussi classique que moderne ! D'une longueur de 37 cm (+ extension de 5 cm), il pourra être associé aux colliers <i>Selena</i> ou <i>Eden</i> qui ajouteront un pendentif juste en-dessous,  ou à d'autres modèles plus longs !", length: "37 cm + 5 cm extension", inserted_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second), updated_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second)},
      %{item_parent_id: item_parent12, price: 35.00, stock: 9, visibility: true, subtitle: "Bracelet Melinda en Argent 925 et Labradorite", description: "", length: "16 cm", inserted_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second), updated_at: NaiveDateTime.truncate(NaiveDateTime.utc_now(), :second)}
      ]
    )
  end
end
